# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic
    username: root
    password: ambrish
    driver-class: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  sleuth:
    sampler:
      percentage: 1.0

# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false

# Logging
logging.level.org.springframework: INFO
